### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by seifeet**
Fellow Swifters,

I’ve  moved the project to Swift 3. As you know, this is a particularly insidious task that has affected a lot of my time. I think it’d be worthwhile to pull it into the project repository in order to get it into the next release.

Thanks!

### CODE REVIEW

**Comment by Krisiacik** [comment]
All the effort is much appreciated. The problem is Travis is crashing monumental. I think it's a case if a curly brace missing as it has 100s of error messages.
Can you pls check you can build everything properly?

**Comment by seifeet** [comment]
Thank you! I had to change travis configuration file from Xcode7 to 8 and now it builds fine.

**Comment by Krisiacik** [comment]
Great job :)
Now we have two options. Either keep this in a Swift3 branch, or merge to master, and do a new Swift3 release.
It's a bit of a dilemma.  What do you guys think is best?

**Comment by seifeet** [comment]
It seems like all the popular projects, like Alamofire, have already switched their main repo to Swift3.
What do you think?

**Comment by zfoltin** [comment]
Merge it @Krisiacik already! 💃 :) If people still need the Swift 2.3 version, they can just use an older version. Talking of versions, the Swift 3 version should be ImageViewer 4.0 with an amazing name.

**Comment by Krisiacik** [comment]
Many thanks for this effort @seifeet !

**Pull request merged**
