### PR TITLE
Adding Podspec for Swift 4 support

### PR DESCRIPTION
**Pull request by mergesort**
This is create a podspec for the Swift 4 support that was added yesterday.

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Unfortunately, there was an [an API breaking change](https://github.com/MailOnline/ImageViewer/pull/155/files#diff-e9dda06d4e6f4f6aca697d802605d6e9), so it would be `5.0.0`. We shouldn't have actually allowed that change, since AFAIK it's orthogonal to the PR's intent.

In any case, thanks for the PR. Please fix it and I will cut a new release.

**Comment by mergesort** [comment]
Updated.

**Comment by zfoltin** [comment]
I think it's perfectly fine to have a major version bump when adding support to a new Swift version.
Should probably update the README though...

**Comment by mergesort** [comment]
@zfoltin Updated the README as well.

**Comment by zfoltin** [comment]
Thanks @mergesort 👍 
@RuiAAPeres if you are happy, let's merge this and push to cocoapods, shall we?

**Pull request merged**
