### PR TITLE
Update to Swift 4.

### PR DESCRIPTION
**Pull request by leviouss**
Hello!
I fixed all the Swift 4 related warnings and errors.

### CODE REVIEW

**Comment by zfoltin** [comment]
LGTM 👍

**Comment by leviouss** [comment]
I see the travis build failed. Is it because you haven't updated to Xcode 9? Cliché, but it works on my machine. :)

**Comment by eriadam** [comment]
Hello. Any plans on merging this?

**Comment by mergesort** [comment]
I would love to know if there are plans to merge this as well. This is the last dependency in my project which has not updated to Swift 4 yet.

**Comment by zfoltin** [comment]
@leviouss can you update `.travis.yml` to use Xcode 9? That should fix the build. Cheers

**Comment by leviouss** [comment]
@zfoltin  Done, should be fine now. I wasn't familiar with Travis, sorry.

**Comment by RuiAAPeres** [comment]
@leviouss thanks, once it passes I will merge this. Thank you.

**Pull request merged**
