### PR TITLE
Swift 3 compatibility

### PR DESCRIPTION
**Pull request by dams229**
Updated the project to compile and run with Swift 3

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
@dams229 could you fix the build? Travis is reporting it as being broken.

**Comment by dams229** [comment]
@RuiAAPeres I'm afraid it's because Travis doesn't support Swift 3 :( Do you know how to update it?

**Comment by zfoltin** [comment]
There is already a PR regarding the Swift 3 update - https://github.com/MailOnline/ImageViewer/pull/58
including green Travis build

**Comment by dams229** [comment]
@zfoltin Sorry I didn't see it, now I see the travis configuration has been edited. So my pull request is useless :)

**Comment by zfoltin** [comment]
Thanks for the effort @dams229 anyways 👍  Closing this as https://github.com/MailOnline/ImageViewer/pull/58 has been merged in.

**Pull request closed without merging**
