### PR TITLE
Swift3 Updates

### PR DESCRIPTION
**Pull request by andreyrd**
Updated for the latest Swift 3 syntax, and @FranciscoAmado even fixed some bugs that popped up in the conversion!

Things got a little messy since updates were done to the master between now and when I created the fork, but it should be at the very least helpful for updating to Swift 3.

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
It's unwise, to mix a lang update (2.2 -> 3.0) plus fixes, in the same PR. It makes it very difficult for us to review.

**Comment by FranciscoAmado** [comment]
An alternative may be a PR with the migration and another, with the fixes, after that one is accepted?! But how would you accept the first if, functionally, the app is broken?

**Comment by andreyrd** [comment]
I'll redo it purely as a Swift 3 update in a day or two. It needs to be redone anyway, since master changed since I started the Swift 3 updates. And then we can figure out those bugs after, if that's what you want.

**Comment by zfoltin** [comment]
Closing this as https://github.com/MailOnline/ImageViewer/pull/58 has been merged in. Could you @FranciscoAmado create a new PR with the fixes if they are still relevant? Many thank 👍

**Pull request closed without merging**
