### PR TITLE
Add single tap to exit and swipe down to exit.

### PR DESCRIPTION
**Pull request by wisonlin**
I think add tap to exit and swipe down to exit will be great feature, user can exit easier.

### CODE REVIEW

**Comment by Krisiacik** [comment]
We'll test it on a real device on Monday and if the UX feels good, we'll merge it.

**Comment by Krisiacik** [comment]
Hi, I did the testing. Unfortunately I cannot merge it in its current state as the change rendered the double tap not working. But double tap is necessary for ScaleToFill zoom functionality.

I mitigated this doubleTap problem with adding 
`singleTapRecognizer.requireGestureRecognizerToFail(doubleTapRecognizer)`

This made it work, but as I a previously indicated, it must also feel good in UX terms. The line above changed the behaviour slightly, now the system actually waits if double tap happens before kicking in the single tap close action. But the issue with Apple''s implementation of this is the time to recognizer failstate is set by Apple (seem to be around 1 second) and we cannot set that to a smaller value.
This makes the UX bad.

If you feel you want this badly, I can image to constrain the double tap to be only recognized in the image bounds. 

If you will push such a change, it will keep the single tap snappy enough as it will not have to wait for double tap to fail. I would then merge it.

**Comment by wisonlin** [comment]
I fixed it by adding `requireGestureRecognizerToFail`, it works.
the single tap will wait around 0.5 second to recognise the double tap failed, we cannot change the time value. cause if we set that value to smaller, the double tap's tap interval will smaller, the user will hard to trigger a double tap. which also makes the UX bad.

**Comment by Krisiacik** [comment]
I did exactly that my previous post. Unfortunately it's not good enough, it makes the UX bad -> the wait time is too long which is unacceptable. The only change that would make sense and I would merge is to constraint the double tap area to the image and single tap area to the remaining black space.

**Pull request closed without merging**
